version: '3.8'

services:
  nginx:
    build: 
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /frontend/nodes_modules
  backend:
    build: 
      context: ./dockerize
      dockerfile: backend
    volumes:
      - ./backend:/app
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d/:/usr/local/etc/php/local.conf.d/"
  mysql:
    image: 'mariadb:10.5'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./mysql:/var/lib/mysql
